//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AnimalsOnPages.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AnimalsOnPages.Resources.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add animal.
        /// </summary>
        public static string AddAnimal_Title {
            get {
                return ResourceManager.GetString("AddAnimal.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string AddAnimalCancelButton {
            get {
                return ResourceManager.GetString("AddAnimalCancelButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Animal Class.
        /// </summary>
        public static string AddAnimalClass {
            get {
                return ResourceManager.GetString("AddAnimalClass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Animal Color.
        /// </summary>
        public static string AddAnimalColor {
            get {
                return ResourceManager.GetString("AddAnimalColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If specified, must be 3-20 characters long.
        /// </summary>
        public static string AddAnimalColorHelper {
            get {
                return ResourceManager.GetString("AddAnimalColorHelper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create.
        /// </summary>
        public static string AddAnimalCreateButton {
            get {
                return ResourceManager.GetString("AddAnimalCreateButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Animal Name.
        /// </summary>
        public static string AddAnimalName {
            get {
                return ResourceManager.GetString("AddAnimalName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name must be 3-20 characters long.
        /// </summary>
        public static string AddAnimalNameHelper {
            get {
                return ResourceManager.GetString("AddAnimalNameHelper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Animal Rank.
        /// </summary>
        public static string AddAnimalRank {
            get {
                return ResourceManager.GetString("AddAnimalRank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Animal Sex.
        /// </summary>
        public static string AddAnimalSex {
            get {
                return ResourceManager.GetString("AddAnimalSex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Animal Sound.
        /// </summary>
        public static string AddAnimalSound {
            get {
                return ResourceManager.GetString("AddAnimalSound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Has to containe 3 repeated parameters, splitted by comma or hyphen.
        /// </summary>
        public static string AddAnimalSoundHelper {
            get {
                return ResourceManager.GetString("AddAnimalSoundHelper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From egg.
        /// </summary>
        public static string Amphibia_Birth {
            get {
                return ResourceManager.GetString("Amphibia_Birth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bare skin.
        /// </summary>
        public static string Amphibia_Covering {
            get {
                return ResourceManager.GetString("Amphibia_Covering", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cold-blooded.
        /// </summary>
        public static string Amphibia_Temperature {
            get {
                return ResourceManager.GetString("Amphibia_Temperature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amphibia.
        /// </summary>
        public static string Animals_AmphibiaClass {
            get {
                return ResourceManager.GetString("Animals_AmphibiaClass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Carnivorous.
        /// </summary>
        public static string Animals_CarnivorousRank {
            get {
                return ResourceManager.GetString("Animals_CarnivorousRank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Female.
        /// </summary>
        public static string Animals_FemaleSex {
            get {
                return ResourceManager.GetString("Animals_FemaleSex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Herbivorous.
        /// </summary>
        public static string Animals_HerbivorousRank {
            get {
                return ResourceManager.GetString("Animals_HerbivorousRank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hybrids.
        /// </summary>
        public static string Animals_HybridsRank {
            get {
                return ResourceManager.GetString("Animals_HybridsRank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Male.
        /// </summary>
        public static string Animals_MaleSex {
            get {
                return ResourceManager.GetString("Animals_MaleSex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mammal.
        /// </summary>
        public static string Animals_MammalClass {
            get {
                return ResourceManager.GetString("Animals_MammalClass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reptile.
        /// </summary>
        public static string Animals_ReptileClass {
            get {
                return ResourceManager.GetString("Animals_ReptileClass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Animals.
        /// </summary>
        public static string Animals_Title {
            get {
                return ResourceManager.GetString("Animals.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Birth.
        /// </summary>
        public static string AnimalsBirth {
            get {
                return ResourceManager.GetString("AnimalsBirth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Class.
        /// </summary>
        public static string AnimalsClass {
            get {
                return ResourceManager.GetString("AnimalsClass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cover color.
        /// </summary>
        public static string AnimalsColor {
            get {
                return ResourceManager.GetString("AnimalsColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Body covering.
        /// </summary>
        public static string AnimalsCovering {
            get {
                return ResourceManager.GetString("AnimalsCovering", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Id.
        /// </summary>
        public static string AnimalsId {
            get {
                return ResourceManager.GetString("AnimalsId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rank.
        /// </summary>
        public static string AnimalsRank {
            get {
                return ResourceManager.GetString("AnimalsRank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sex.
        /// </summary>
        public static string AnimalsSex {
            get {
                return ResourceManager.GetString("AnimalsSex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sound.
        /// </summary>
        public static string AnimalsSound {
            get {
                return ResourceManager.GetString("AnimalsSound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Body temperature.
        /// </summary>
        public static string AnimalsTemperature {
            get {
                return ResourceManager.GetString("AnimalsTemperature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AnimalsOnPages.
        /// </summary>
        public static string CiteName_Title {
            get {
                return ResourceManager.GetString("CiteName.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grey.
        /// </summary>
        public static string ColorId1 {
            get {
                return ResourceManager.GetString("ColorId1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BrownBrown.
        /// </summary>
        public static string ColorId2 {
            get {
                return ResourceManager.GetString("ColorId2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LightGrey.
        /// </summary>
        public static string ColorId3 {
            get {
                return ResourceManager.GetString("ColorId3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LightGrey.
        /// </summary>
        public static string ColorId4 {
            get {
                return ResourceManager.GetString("ColorId4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Green.
        /// </summary>
        public static string ColorId5 {
            get {
                return ResourceManager.GetString("ColorId5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string DeleteButton {
            get {
                return ResourceManager.GetString("DeleteButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Animal Id.
        /// </summary>
        public static string Details_Title {
            get {
                return ResourceManager.GetString("Details.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find out more.
        /// </summary>
        public static string DetailsButton {
            get {
                return ResourceManager.GetString("DetailsButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Live birth.
        /// </summary>
        public static string Mammal_Birth {
            get {
                return ResourceManager.GetString("Mammal_Birth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hair.
        /// </summary>
        public static string Mammal_Covering {
            get {
                return ResourceManager.GetString("Mammal_Covering", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hematothermal.
        /// </summary>
        public static string Mammal_Temperature {
            get {
                return ResourceManager.GetString("Mammal_Temperature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wolf.
        /// </summary>
        public static string NameId1 {
            get {
                return ResourceManager.GetString("NameId1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bear.
        /// </summary>
        public static string NameId2 {
            get {
                return ResourceManager.GetString("NameId2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Crocodile.
        /// </summary>
        public static string NameId3 {
            get {
                return ResourceManager.GetString("NameId3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Turtle.
        /// </summary>
        public static string NameId4 {
            get {
                return ResourceManager.GetString("NameId4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Frog.
        /// </summary>
        public static string NameId5 {
            get {
                return ResourceManager.GetString("NameId5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add animal.
        /// </summary>
        public static string NavbarAddAnimal {
            get {
                return ResourceManager.GetString("NavbarAddAnimal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Animals.
        /// </summary>
        public static string NavbarAnimals {
            get {
                return ResourceManager.GetString("NavbarAnimals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From egg.
        /// </summary>
        public static string Reptile_Birth {
            get {
                return ResourceManager.GetString("Reptile_Birth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scales.
        /// </summary>
        public static string Reptile_Covering {
            get {
                return ResourceManager.GetString("Reptile_Covering", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cold-blooded.
        /// </summary>
        public static string Reptile_Temperature {
            get {
                return ResourceManager.GetString("Reptile_Temperature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Owoo-oo-oo.
        /// </summary>
        public static string SoundId1 {
            get {
                return ResourceManager.GetString("SoundId1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ur-r-r.
        /// </summary>
        public static string SoundId2 {
            get {
                return ResourceManager.GetString("SoundId2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grunt, grunt, grunt.
        /// </summary>
        public static string SoundId3 {
            get {
                return ResourceManager.GetString("SoundId3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creek, creek, creek.
        /// </summary>
        public static string SoundId4 {
            get {
                return ResourceManager.GetString("SoundId4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kwa, kwa, kwa.
        /// </summary>
        public static string SoundId5 {
            get {
                return ResourceManager.GetString("SoundId5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back to animals.
        /// </summary>
        public static string ToAnimalsButton {
            get {
                return ResourceManager.GetString("ToAnimalsButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update animal.
        /// </summary>
        public static string UpdateAnimal {
            get {
                return ResourceManager.GetString("UpdateAnimal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update animal Id .
        /// </summary>
        public static string UpdateAnimal_Title {
            get {
                return ResourceManager.GetString("UpdateAnimal.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update.
        /// </summary>
        public static string UpdateAnimalButton {
            get {
                return ResourceManager.GetString("UpdateAnimalButton", resourceCulture);
            }
        }
    }
}
